[package]
name = "rustpy_gpu"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustpy_gpu"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
ndarray = "0.15.6"
numpy = "0.16"
