[package]
name = "rustpy_gpu"
version = "0.1.0"
authors = ["Wilhelm Ågren <wilhelmagren98@gmail.com>"]
edition = "2021"

[lib]
name = "rustpy_gpu"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.17"
features = ["extension-module"]

[dependencies.numpy]
version = "0.17"